[#IP-306] Handle Cosmos unix timestamp format
pagopa/io-functions-services pull request #145
Opened 2021-07-09 15:29 UTC by AleDore

#### List of Changes

* add usage of `fromUnixTime` while comparing cosmos timestamp with `optOutEmailSwitchDate`
* minor test refactor
* Refactor of handler in a more functional way

#### Motivation and Context

This solve a problem while comparing a Date made from a Unix Timestamp and another one made from Timestamp expressed in millisecond.

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-07-13 15:53 UTC, balanza approved these changes

2021-07-13 15:53 UTC, balanza commented on StoreMessageContentActivity/__tests__/handler.test.ts
> +console.log(isBefore(nowTimestamp, aFutureOptOutEmailSwitchDate));
do we need these logs?

2021-07-13 15:58 UTC, BurnedMarshal requested changes

2021-07-13 15:58 UTC, BurnedMarshal commented on StoreMessageContentActivity/__tests__/handler.test.ts
> +const nowTimestamp = Math.floor(new Date().getTime() / 1000);
```suggestion
const lastUpdateTimestamp = Math.floor(new Date().getTime() / 1000);
```

2021-07-13 16:07 UTC, AleDore commented on StoreMessageContentActivity/__tests__/handler.test.ts
> +console.log(isBefore(nowTimestamp, aFutureOptOutEmailSwitchDate));
Nope I'll remove it

2021-07-14 07:28 UTC, BurnedMarshal approved these changes
LGTM

2021-07-14 07:29 UTC, merged