Iocit 195
pagopa/io-functions-services pull request #237
Opened 2022-11-17 17:01 UTC by Garma00

#### List of Changes

* Update `@pagopa/io-functions-commons`;
* Set the `ttl` during the upsert when the user does not exist;

#### Motivation and Context

We need to set the ttl directly when creating the entry of the message status in order to solve an issue with cosmos.

#### How Has This Been Tested?

Unit test
#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-11-21 08:45 UTC, gquadrati requested changes

2022-11-21 11:55 UTC, gquadrati commented on ProcessMessage/handler.ts
> +                  context.log.error(`${logPrefix}|ERROR=${JSON.stringify(e)}`);
```suggestion
                  context.log.error(`${logPrefix}|PROFILE_NOT_FOUND|UPSERT_STATUS=REJECTED|ERROR=${JSON.stringify(e)}`);
```

2022-11-21 11:56 UTC, gquadrati approved these changes
LGTM other than this small change

2022-11-21 13:34 UTC, fabriziopapi approved these changes

2022-11-22 10:14 UTC, fabriziopapi approved these changes

2022-11-23 14:13 UTC, merged